### PR TITLE
Domain, update serial on changes in either domain or record. This has…

### PR DESCRIPTION
**Pull request by AdSchellevis**
… one minor downside. It needs two updates to the configuration when changing a record (record --> parent domain)

### CODE REVIEW

**Comment by mimugmail** [comment]
Does this also higher the serial when only changing TTL in Domain grid?

**Comment by AdSchellevis** [comment]
@mimugmail yes, if anything changes, it updates, due to https://github.com/mimugmail/plugins/pull/2/files#diff-f8b4155d129ca458b6dbf009bc94b8bfR39

**Comment by mimugmail** [comment]
Thanks Ad :)

**Comment by mimugmail** [comment]
Looks very nice .. also the preselection of correct domain when adding a record .. really cool :)
Lets make a public dev and wait for some feedback :)

**Pull request merged**
